hayvanlar/api/urls.py
from django.urls import path

from hayvanlar.api import views as api_views
urlpatterns = [
    path('animals/',api_views.AnimalsListCreateAPIView.as_view(),name='animalslist'),
    path('owners/',api_views.OwnersListCreateAPIView.as_view(),name='ownerslist'),
    path('animals/<int:pk>',api_views.AnimalsDetailCreateAPIView.as_view(),name='animalsdetail'),
    path('owners/<int:pk>',api_views.OwnersDetailCreateAPIView.as_view(),name='ownersdetail'),
 

]

hayvanlar/urls.py
from django.urls import path

# from .views import IndexPageView,AnimalCreateView,AnimalUpdateView,AnimalDeleteView,AnimalDetailView,OwnerCreateView,OwnerUpdateView,OwnerDeleteView,OwnerDetailView
from . import views

app_name="hayvanlar"

urlpatterns = [
    path('', views.index, name="index"),
    path('animals/', views.animals, name="animals"),
    path('animalowners/', views.owners, name="animalowners"),
    path('animal-delete/<int:id>/',views.animal_delete,name = "animal_delete"),
    path('owner-delete/<int:id>/',views.owner_delete,name = "owner_delete"),
    path('animal/update/<int:id>/',views.animal_update,name="animal-update"),
    path('animal/detail/<int:id>/',views.animal_detail,name="animal_detail"),
    path('owner/detail/<int:id>/',views.owner_detail,name="owner_detail"),
    path('owner/update/<int:id>/',views.owner_update, name = "owner-update"),
    path('warning',views.alertmessage, name = "alertmessage"),



# ------------CLASS BASED VİEWS-----------------------
    # path('', IndexPageView.as_view(), name="index"),
    # path('animals', AnimalCreateView.as_view(), name="animals"),
    # path('animalowners/', OwnerCreateView.as_view(), name="animalowners"),
    # path('animal-delete/<pk>',AnimalDeleteView.as_view(),name = "animal_delete"),
    # path('owner-delete/<pk>',OwnerDeleteView.as_view(),name = "owner_delete"),
    # path('animal/update/<pk>/',AnimalUpdateView.as_view(),name="animal-update"),
    # path('animal/detail/<pk>/',AnimalDetailView.as_view(),name="animal_detail"),
    # path('owner/detail/<pk>/',OwnerDetailView.as_view(),name="owner_detail"),
    # path('owner/update/<pk>',OwnerUpdateView.as_view(), name = "owner-update"),
    # path('warning',views.alertmessage, name = "alertmessage"),
]

user/urls.py
from django.urls import path
from . import views
# from .views import UserCreateView,UserLoginView
app_name="user"

urlpatterns = [
    path('login/', views.sign_in, name="sign_in"),
    path('register/', views.register, name="register"),
    path('logout/', views.sign_out, name="sign_out"),



    # Generic paths
    # path('login/', UserLoginView.as_view(), name="sign_in"),
    # path('register/', UserCreateView.as_view(), name="register"),

]

veteriner/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hayvanlar.urls')),
    path('user/', include('user.urls')),
    path('api/', include('hayvanlar.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

hayvanlar/models.py
from django.db import models
from django.urls import reverse


class AnimalOwners(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    address = models.TextField(max_length=40)
    email = models.EmailField(max_length=30)
    phone = models.CharField(max_length=11)

    def __str__(self):
        return self.name
    @property
    def get_animals(self):
        animals = self.animals_set.all()
        return animals 
    def get_absolute_url(self):
        return reverse("hayvanlar:owner_detail", args=[str(self.id)])

class Animals(models.Model):
    type = models.CharField(max_length=15)
    genus = models.CharField(max_length=15)
    name = models.CharField(max_length=20)
    age=models.IntegerField(default=0)
    owner=models.ForeignKey(AnimalOwners, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=100)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("hayvanlar:animal_detail", args=[str(self.id)])

hayvanlar/forms.py
from .models import  Animals,AnimalOwners
from django.forms import ModelForm


class OwnersForm(ModelForm):
   class Meta:
        model = AnimalOwners
        fields = ['name', 'surname', 'email', 'phone','address']

class AnimalsForm(ModelForm):
   class Meta:
        model = Animals
        fields = ['type', 'genus', 'name', 'age', 'owner', 'description']

hayvanlar/api/views.py
from rest_framework import generics
from hayvanlar.api.serializers import AnimalsSerializers,AnimalOwnersSerializers
from hayvanlar.models import AnimalOwners,Animals
from rest_framework.permissions import IsAuthenticated
from .permissions import IsAdminUserOrReadOnly
from .pagination import StandardResultsSetPagination


class AnimalsListCreateAPIView(generics.ListCreateAPIView):
    queryset=Animals.objects.all()
    serializer_class=AnimalsSerializers
    permission_classes=[IsAuthenticated]
    pagination_class= StandardResultsSetPagination

class OwnersListCreateAPIView(generics.ListCreateAPIView):
    queryset=AnimalOwners.objects.all()
    serializer_class=AnimalOwnersSerializers
    permission_classes=[IsAuthenticated]
    pagination_class= StandardResultsSetPagination


class AnimalsDetailCreateAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset=Animals.objects.all()
    serializer_class=AnimalsSerializers
    permission_classes=[IsAdminUserOrReadOnly,IsAuthenticated]


class OwnersDetailCreateAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset=AnimalOwners.objects.all()
    serializer_class=AnimalOwnersSerializers
    permission_classes=[IsAdminUserOrReadOnly,IsAuthenticated]

hayvanlar/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import AnimalsForm,OwnersForm
from hayvanlar.models import AnimalOwners,Animals
from django.contrib import messages
from .models import *
from .mixins import EditLoginRequiredMixin,AdminLoginRequiredMixin
from django.views import generic
from django.contrib.auth.decorators import user_passes_test,login_required
from django.shortcuts import reverse
# from django.urls import reverse_lazy
# from django.db.models import Q
# from django.core.paginator import Paginator



# ------------FUNCTON BASED VİEWS-----------------------
def index(request):

    return render(request,"index.html")

@login_required(login_url = "user:sign_in")
def animals(request):
    current_user = request.user
    hayvanlar=Animals.objects.all()
    # From here used Data Tables for Search
    # query=request.GET.get('search')
    # paginator = Paginator(hayvanlar, 10)
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
    form=AnimalsForm()
    if request.method == 'POST':
        form = AnimalsForm(request.POST)
        try:
            print(form.errors)
            if form.is_valid:
                form.save()
                messages.success(request,"You added animal successfully")
                return redirect("hayvanlar:animals")
        except(ValueError):
                messages.warning(request,"Please fill the form correctly")
                return redirect("hayvanlar:animals")

    # From here used Data Tables for Search
    # if query:
    #     hayvanlar=Hayvan.objects.filter(Q(type__icontains=query) | Q(genus__icontains=query) | Q(name__icontains=query) )
    #     if hayvanlar: 
    #         context={"hayvanlar":hayvanlar,"form":form,"page_obj":page_obj}
    #         return render(request,"animals.html",context)
    #     else:
    #         messages.warning(request,"Aradığınız Kriterlerde Kayıt Bulunamadı.")
    #         context={"hayvanlar":hayvanlar,"form":form,"page_obj":page_obj}
    #         return render(request,"animals.html",context)

    context={"hayvanlar":hayvanlar,"form":form,"current_user":current_user}
    return render(request,"animals.html",context)


@user_passes_test(lambda u: u.is_superuser,login_url = "hayvanlar:alertmessage")
def animal_update(request,id):
    hayvanlar=Animals.objects.all()
    instance = get_object_or_404(Animals,id = id)
    form = AnimalsForm(request.POST or None,instance = instance)
    try:
        if form.is_valid():
            form.save()
            messages.success(request,"Data updated successfully")
            return redirect(request.META.get('HTTP_REFERER'))
    except(ValueError):
        messages.warning(request,"Please fill the form correctly") 
        return render(request,"edit_animals.html",context)

    context={"hayvanlar":hayvanlar,"form":form}
    return render(request,"edit_animals.html",context)

@user_passes_test(lambda u: u.is_superuser,login_url = "hayvanlar:alertmessage")
def animal_delete(request,id):
    animals = get_object_or_404(Animals,id = id)
    animals.delete()
    messages.success(request,"Data deleted successfully")

    return redirect("hayvanlar:animals")

@login_required(login_url = "user:sign_in")
def animal_detail(request,id):
    form = get_object_or_404(Animals,id = id)
    context={"form":form}
    return render(request,"animal_detail.html",context)

@login_required(login_url = "user:sign_in")
def owners(request):

    owners=AnimalOwners.objects.all()
    form=OwnersForm()
    if request.method == 'POST':
        form = OwnersForm(request.POST)
        try:
            if form.is_valid:
                form.save()
                messages.success(request,"You added animal owner successfully")
                return redirect("hayvanlar:animalowners")
        except(ValueError):
            messages.warning(request,"Please fill the form correctly")
            return redirect("hayvanlar:index")
    context={"owners":owners,"form":form}
    return render(request,"animalowners.html",context)


@user_passes_test(lambda u: u.is_superuser,login_url = "hayvanlar:alertmessage")
def owner_update(request,id):
     
    owners=AnimalOwners.objects.all()
    instance = get_object_or_404(AnimalOwners,id = id)
    form = OwnersForm(request.POST or None,instance = instance)
    try:
        if form.is_valid():
            form.save()
            messages.success(request,"Data updated successfully")
            return redirect(request.META.get('HTTP_REFERER'))
    except(ValueError):
                messages.warning(request,"Please fill the form correctly") 
                return render(request,"edit_owner.html",context)
    context={"owners":owners,"form":form}
    return render(request,"edit_owner.html",context)


@user_passes_test(lambda u: u.is_superuser,login_url = "hayvanlar:alertmessage")
def owner_delete(request,id):
    owner = get_object_or_404(AnimalOwners,id = id)
    owner.delete()
    messages.success(request,"Data deleted successfully")
    return redirect("hayvanlar:animalowners")


@login_required(login_url = "user:sign_in")
def owner_detail(request,id):
    form = get_object_or_404(AnimalOwners,id = id)
    hayvan = form.animals_set.all()
    context={"form":form,"hayvan":hayvan}
    return render(request,"owner_detail.html",context)
    

@login_required(login_url = "user:sign_in")
def alertmessage(request):
	messages.warning(request,'You have no permission to do this')
	return redirect("hayvanlar:index")




# ------------CLASS BASED VİEWS-----------------------

# class IndexPageView(generic.TemplateView):
#     template_name = "index.html"

# class AnimalCreateView(EditLoginRequiredMixin,generic.CreateView,generic.ListView):
#     template_name = "animals.html"
#     form_class = AnimalsForm
#     context_object_name = "hayvanlar"
#     def get_success_url(self):
#         return reverse("hayvanlar:animals")
#     def get_queryset(self):
#         hayvanlar=Animals.objects.all()
#         return hayvanlar
#     def form_valid(self, form):
#         form = AnimalsForm(self.request.POST)
#         try:
#             if form.is_valid:
#                 forms = form.save(commit=False)
#                 forms.save()
#                 messages.success(self.request,"You added animal successfully")
#                 return super(AnimalCreateView, self).form_valid(form)
#         except(ValueError):
#                 messages.warning(self.request,"Please fill the form correctly")
#                 return super(AnimalCreateView, self)

# class AnimalUpdateView(AdminLoginRequiredMixin,generic.UpdateView,generic.ListView):
#     template_name = "edit_animals.html"
#     form_class = AnimalsForm
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['hayvanlar'] = Animals.objects.all()
#         return context
#     def get_success_url(self):
#         return reverse("hayvanlar:animals")
#     def get_queryset(self):
#         animal=Animals.objects.filter(id=self.kwargs['pk'])
#         return animal 
#     def form_valid(self, form):
#         form.save()
#         messages.info(self.request, "You have successfully updated this animal")
#         return super(AnimalUpdateView, self).form_valid(form)

# class AnimalDeleteView(AdminLoginRequiredMixin,generic.DeleteView):
#     template_name = "animal_delete.html"
#     def get_success_url(self):
#         messages.info(self.request, "You have successfully deleted")
#         return reverse("hayvanlar:animals")
#     def get_queryset(self):
#         animal=Animals.objects.filter(id=self.kwargs['pk'])
#         return animal 

# class AnimalDetailView(AdminLoginRequiredMixin,generic.DetailView):
#     template_name = "animal_detail.html"
#     context_object_name = "form"
#     def get_queryset(self):
#         animal=Animals.objects.filter(id=self.kwargs['pk'])
#         return animal 

# class OwnerCreateView(EditLoginRequiredMixin,generic.CreateView,generic.ListView):
#     template_name = "animalowners.html"
#     form_class = OwnersForm
#     context_object_name = "owners"
#     def get_success_url(self):
#         return reverse("hayvanlar:animalowners")
#     def get_queryset(self):
#         owners=AnimalOwners.objects.all()
#         return owners
#     def form_valid(self, form):
#         form = OwnersForm(self.request.POST)
#         if form.is_valid:
#             forms = form.save(commit=False)
#             forms.save()
#             messages.success(self.request,"You added owner successfully")
#             return super(OwnerCreateView, self).form_valid(form)

# class OwnerUpdateView(AdminLoginRequiredMixin,generic.UpdateView,generic.ListView):
#     template_name = "edit_owner.html"
#     form_class = OwnersForm
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['owners'] = AnimalOwners.objects.all()
#         return context
#     def get_success_url(self):
#         return reverse("hayvanlar:animalowners")
#     def get_queryset(self):
#         animal=AnimalOwners.objects.filter(id=self.kwargs['pk'])
#         return animal 
#     def form_valid(self, form):
#         form.save()
#         messages.info(self.request, "You have successfully updated this owner")
#         return super(OwnerUpdateView, self).form_valid(form)

# class OwnerDeleteView(AdminLoginRequiredMixin,generic.DeleteView):
#     template_name = "owner_delete.html"
#     def get_success_url(self):
#         messages.info(self.request, "You have successfully deleted")
#         return reverse("hayvanlar:animalowners")
#     def get_queryset(self):
#         owner=AnimalOwners.objects.filter(id=self.kwargs['pk'])
#         return owner 

# class OwnerDetailView(AdminLoginRequiredMixin,generic.DetailView):
#     template_name = "owner_detail.html"
#     context_object_name = "form"
#     def get_queryset(self):

hayvanlar/templates/alertmessage.html
{% extends 'layout.html' %}
{% block style %}

{% endblock  %}
{% block body %}





{% endblock  %}

hayvanlar/templates/animalowners.html
{% extends 'layout.html' %} 
{% load static %}
{% block style %}
<style>
  body {
    padding: 0px;
    margin: 0px;
    width: 100%;
    height: 100%;
    background-image:linear-gradient(rgba(27, 24, 24, 0.4), rgba(131, 119, 119, 0.4)), url('{% static "images/vf-issuelanding-vet-checking-heartbeat-of-brown-and-white-cat.jpg" %}');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    height: calc(100vh);
    overflow-x: hidden;

  }
  .text-center h3{
    color:rgb(238, 235, 235);
    font-weight: 620;
  }
</style>
{% endblock %} {% block body %}
<div class="container mt-5">
  <table id="example" class="display" style="width:100%">
    <thead class="table_head">
        <tr>
          <th scope="col">id</th>
          <th scope="col">Name</th>
          <th scope="col">Surname</th>
          <th scope="col">E-mail</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Adress</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
      {% for owner in owners %}
      <tr>
        <th scope="row">{{owner.id}}</th>
        <td>
          <a class="nav-link" href="{%url 'hayvanlar:owner_detail' owner.id %}">{{owner.name}}</a>
        </td>
        <td>{{owner.surname}}</td>
        <td>{{owner.email}}</td>
        <td>{{owner.phone}}</td>
        <td>{{owner.address}}</td>
        <td>
          <a href="{%url 'hayvanlar:owner-update' owner.id %}">
            <button class="btn btn-warning">Edit</button></a
          >
        </td>
        <td>
          <a href="{%url 'hayvanlar:owner_delete' owner.id %}">
            <button class="btn btn-danger">Delete</button></a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>
 



<div class="row my-5">
  <div class="col-md-3"></div>
  <div class="col-md-6 mx-3">
    <form
    class="sahip-form"
    action="{%url 'hayvanlar:animalowners' %}"
    method="post"
    id="form-control"
    >
    {% csrf_token %}
    <div class="text-center">
      <h3 >Add Animal Owner</h3>
    </div>
    
    <div class="form-group label-floating is-empty">
      <label class="control-label">Name</label><br />
      <div class="form-group label-floating is-empty">
        <input class="form-control" type="text" name="name" maxlength="20" required="" id="id_name">
      </div>
      <span class="material-input"></span>
    </div>


    <div class="form-group label-floating is-empty">
      <label class="control-label">Surname</label><br />
      <div class="form-group label-floating is-empty">
        <input class="form-control" type="text" name="surname" maxlength="20" required="" id="id_surname">
      </div>
      <span class="material-input"></span>
    </div>


    <div class="form-group label-floating is-empty">
      <label class="control-label">Email</label><br />
      <div class="form-group label-floating is-empty">
        <input class="form-control" type="email" name="email" maxlength="30" required="" id="id_email">
      </div>
      <span class="material-input"></span>
    </div>


    <div class="form-group label-floating is-empty">
      <label class="control-label">Phone Number</label><br />
      <input
        type="text"
        class="form-control"
        name="phone"
        maxlength="11"
        required=""
        id="id_phone"
        pattern="[0]{1}[5]{1}[0-9]{2}[0-9]{3}[0-9]{2}[0-9]{2}"
        oninvalid="this.setCustomValidity('Lütfen geçerli formatta bir telefon numarası giriniz. Örneğin: 05334442222')"
        oninput="this.setCustomValidity('')"
      />

    </div>
 

    <div class="form-group label-floating is-empty">
      <label class="control-label">Owners Adress </label>
      <div class="form-group label-floating is-empty">
        <textarea class="form-control" name="address" cols="20" rows="5" maxlength="40" required="" id="id_address"></textarea>
      </div>
      <span class="material-input"></span>
    </div>
  
    <div class="form-group">
      <button type="submit" class="btn btn-danger btn-block">ADD</button>
    </div>
  </form>

  </div>
</div>

 
</div>

{% endblock %}
{% block script %} 


{% endblock %}

hayvanlar/templates/animals.html
{% extends 'layout.html' %} 
{% load static %}
{% block style %}
<style>

  body {
    padding: 0px;
    margin: 0px;
    width: 100%;
    height: 100%;
    background-image:linear-gradient(rgba(27, 24, 24, 0.2), rgba(131, 119, 119, 0.2)), url('{% static "images/groupDog.jpg" %}');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    height: calc(100vh );
    overflow-x: hidden;

  }
  .text-center h3{
    color:rgb(238, 235, 235);
    font-weight: 620;
  }

</style>
{% endblock %} {% block body %}
<div class="container mt-5">
  <table id="example" class="display" style="width:100%">
    <thead class="table_head">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Type</th>
          <th scope="col">Genus</th>
          <th scope="col">Name</th>
          <th scope="col">Age</th>
          <th scope="col">Owner</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
      {% for hayvan in hayvanlar %}
      <tr>
        <th scope="row">{{hayvan.id}}</th>
        <td>{{hayvan.type}}</td>
        <td>{{hayvan.genus}}</td>
        <td><a class="nav-link" href="{%url 'hayvanlar:animal_detail' hayvan.id %}">{{hayvan.name}}</a></td>  
        <td>{{hayvan.age}}</td>
        <td>{{hayvan.owner}}</td>
        <td>
          <a href="{% url 'hayvanlar:animal-update' hayvan.id%}">
            <button class="btn btn-warning">Edit</button></a
          >
        </td>
        <td>
          <a href="{% url 'hayvanlar:animal_delete' hayvan.id%}">
            <button class="btn btn-danger">Delete</button></a
          >
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>

<div class="row my-3">
  <div class="col-md-3"></div>
  <div class="col-md-6 ">
  <form
    class="hayvan-form"
    action="{%url 'hayvanlar:animals' %}"
    method="post"
    id="form-control"
  >
    {% csrf_token %}
    <div class="text-center">
      <h3>Add Animal</h3>
    </div>

    <div class="form-group label-floating is-empty">
      <label class="control-label"> Type of animal</label><br />

      <div class="form-group label-floating is-empty">
        <input type="text"  class="form-control" name="type" maxlength="15" required="" id="id_type">
      </div>
    </div>


    <div class="form-group label-floating is-empty">
      <label class="control-label">Genus of animal</label><br />

      <div class="form-group label-floating is-empty">
        <input type="text"  class="form-control" class="form-control" name="genus" maxlength="15" required="" id="id_genus">
      </div>
    </div>


    <div class="form-group label-floating is-empty">
      <label class="control-label">Name</label><br />
      <div class="form-group label-floating is-empty">
        <input type="text" class="form-control" name="name" maxlength="20" required="" id="id_name">
      </div>
    </div>


    <div class="form-group label-floating is-empty">
      <label class="control-label"> Age</label><br />

      <div class="form-group label-floating is-empty" id="price">
        <input type="number"  class="form-control" name="age" value="0" required="" id="id_age">
      </div>
    </div>
 

    <div class="form-group label-floating is-empty">
      <label class="control-label">Owner </label><br />
      <div class="form-group label-floating is-empty">
        {{form.owner}}

  </div>
</div>



    <div class="form-group label-floating is-empty">
      <label class="control-label">About the animal </label>
      <div class="form-group label-floating is-empty">
        <textarea name="description" cols="40" rows="5"  class="form-control"  maxlength="100" required="" id="id_description"></textarea>
      </div>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-danger btn-block">ADD</button>
    </div>
  </form>
</div>
</div>
</div>

{% endblock %} 
{% block script %} 

  <script>
   let owner= document.getElementById('id_owner')
   owner.classList = "form-control"
  </script>

{% endblock %}

hayvanlar/templates/edit_animals.html
{% extends 'layout.html' %}
{% load static %}
{% block style %}
<style>
  body {
    padding: 0px;
    margin: 0px;
    width: 100%;
    height: 100%;
    background-image:linear-gradient(rgba(27, 24, 24, 0.5), rgba(131, 119, 119, 0.5)), url('{% static "images/groupDog.jpg" %}');
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    height: calc(100vh );
    overflow-x: hidden;

  }



</style>
{% endblock  %}
{% block body %}
<div class="container mt-5">

    <table id="example" class="display" style="width:100%">
        <thead class="table_head">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Type</th>
              <th scope="col">Genus</th>
              <th scope="col">Name</th>
              <th scope="col">Age</th>
              <th scope="col">Owner</th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
          {% for hayvan in hayvanlar %}
          <tr>
            <th scope="row">{{hayvan.id}}</th>
            <td>{{hayvan.type}}</td>
            <td>{{hayvan.genus}}</td>
            <td><a class="nav-link" href="{%url 'hayvanlar:animal_detail' hayvan.id %}">{{hayvan.name}}</a></td>  
            <td>{{hayvan.age}}</td>
            <td>{{hayvan.owner}}</td>
            <td>
              <a href="{% url 'hayvanlar:animal-update' hayvan.id%}">
                <button class="btn btn-warning">Edit</button></a
              >
            </td>
            <td>
              <a href="{% url 'hayvanlar:animal_delete' hayvan.id%}">
                <button class="btn btn-danger">Delete</button></a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
    
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">

    <form class="hayvan-form mt-5" action="" method="post" id="form-control">

      {% csrf_token %}
      <div class="text-center"> <h3>Edit Animals </h3></div> 
      <div class="form-group label-floating is-empty">
          <label  class="control-label"> Type of animal</label><br>
          <div class="form-group label-floating is-empty">
            <input type="text" name="type" class="form-control" value="{{form.type.value}}" maxlength="15" required="" id="id_type">
          </div> 
          <span class="material-input"></span>
      </div>

      
      <div class="form-group label-floating is-empty">
          <label class="control-label">Genus of animal</label><br>
          <div class="form-group label-floating is-empty">
            <input type="text" name="genus" value="{{form.genus.value}}"  class="form-control" maxlength="15" required="" id="id_genus">
          </div>
          <span class="material-input"></span>
      </div>
     
      <div class="form-group label-floating is-empty">
          <label class="control-label">Name</label><br>
          <div class="form-group label-floating is-empty">
            <input type="text" name="name" value="{{form.name.value}}" class="form-control" maxlength="20" required="" id="id_name">
          </div> 
          <span class="material-input"></span>
      </div>
     
      <div class="form-group label-floating is-empty">
          <label class="control-label">Age</label><br>
          <div class="form-group label-floating is-empty " id="price">
            <input type="number" name="age" value="{{form.age.value}}" class="form-control" required="" id="id_age">
          </div>
          <span class="material-input"></span>
      </div>

      
      <div class="form-group label-floating is-empty">
          <label class="control-label">Owner</label><br>
          <div class="form-group label-floating is-empty">
            {{form.owner}}
          </div>
          <span class="material-input"></span>
      </div>
 
      
      <div class="form-group label-floating is-empty">
          <label class="control-label">About the animal </label>
          <div class="form-group label-floating is-empty">
            <textarea name="description"  class="form-control" cols="40" rows="5" maxlength="100" required="" id="id_description">{{form.description.value}}</textarea>
          </div>
          <span class="material-input"></span>
      </div>

      <div class="form-group">
          <button type="submit" class="btn btn-danger btn-block">EDIT</button>
      </div>
      </form>
  

  </div>
</div>
















</div>




{% endblock  %}


{% block script %} 

  <script>
   let owner= document.getElementById('id_owner')
   owner.classList = "form-control"
  </script>

{% endblock %}